# Generated by Django 5.1.6 on 2025-05-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformasiLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
